apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myweb-deploy  
spec:
  replicas: 1
  selector:
    matchLabels:
        env: testing

  template:
    metadata:
     name: myweb-deploy
     labels:
       env: testing
       dc: "2"
       region: IN
    spec:
     containers:
     - name: myweb-con
       image: shirsha30/httpd_server:latest
       ports:
       - containerPort: 80
       volumeMounts:
       - name: web-vol1
         mountPath: /var/www/html/
     volumes:
     - name: web-vol1
       persistentVolumeClaim:
         claimName: deploy-pvc1