apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myweb-deploy  
  labels:
    env: testing
spec:
  replicas: 1
  selector:
    matchLabels:
        env: testing
  strategy:
    type: Rolling update

  template:
    metadata:
     labels:
       env: testing
       dc: "2"
       region: IN
    spec:
     containers:
     - name: myweb-con
       image: shirsha30/httpd_server:latest
       ports:
       - containerPort: 80
         
      