apiVersion: v1
kind: Service
metadata:
  name: myweb-deploy
  labels:
    app: myweb-deploy
spec:
  ports:
  - port: 80
    nodePort: 31550
  selector:
     env: production
     dc: "2"
  type: NodePort